# @package _global_

dim: 25
n_particles: 1
spatial_dim: 25

energy:
  _target_: adjoint_samplers.energies.bayesian_logreg_energy.BayesianLogRegEnergy
  dim: ${dim}
  dataset: german
  prior_scale: 1.0

evaluator:
  _target_: adjoint_samplers.components.generic_evaluator.GenericEnergyEvaluator
