# @package _global_

dim: 2
n_particles: 1
spatial_dim: 2

energy:
  _target_: adjoint_samplers.energies.viz_energies.CheckerboardEnergy
  dim: ${dim}
  grid_size: 4
  sharpness: 10.0

evaluator:
  _target_: adjoint_samplers.components.generic_evaluator.GenericEnergyEvaluator
