# @package _global_

dim: 2
n_particles: 1
spatial_dim: 2

energy:
  _target_: adjoint_samplers.energies.viz_energies.NestedRingsEnergy
  dim: ${dim}
  r_inner: 2.0
  r_outer: 5.0
  width: 0.3
  w_outer: 0.8

evaluator:
  _target_: adjoint_samplers.components.generic_evaluator.GenericEnergyEvaluator
